// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/israel-duff/ledger-system/pkg/db/model"
)

func newUserModel(db *gorm.DB, opts ...gen.DOOption) userModel {
	_userModel := userModel{}

	_userModel.userModelDo.UseDB(db, opts...)
	_userModel.userModelDo.UseModel(&model.UserModel{})

	tableName := _userModel.userModelDo.TableName()
	_userModel.ALL = field.NewAsterisk(tableName)
	_userModel.ID = field.NewString(tableName, "id")
	_userModel.CreatedAt = field.NewTime(tableName, "created_at")
	_userModel.UpdatedAt = field.NewTime(tableName, "updated_at")
	_userModel.DeletedAt = field.NewField(tableName, "deleted_at")
	_userModel.EmailAddress = field.NewString(tableName, "email_address")
	_userModel.PhoneNumber = field.NewString(tableName, "phone_number")

	_userModel.fillFieldMap()

	return _userModel
}

type userModel struct {
	userModelDo userModelDo

	ALL          field.Asterisk
	ID           field.String
	CreatedAt    field.Time
	UpdatedAt    field.Time
	DeletedAt    field.Field
	EmailAddress field.String
	PhoneNumber  field.String

	fieldMap map[string]field.Expr
}

func (u userModel) Table(newTableName string) *userModel {
	u.userModelDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userModel) As(alias string) *userModel {
	u.userModelDo.DO = *(u.userModelDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userModel) updateTableName(table string) *userModel {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewString(table, "id")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.UpdatedAt = field.NewTime(table, "updated_at")
	u.DeletedAt = field.NewField(table, "deleted_at")
	u.EmailAddress = field.NewString(table, "email_address")
	u.PhoneNumber = field.NewString(table, "phone_number")

	u.fillFieldMap()

	return u
}

func (u *userModel) WithContext(ctx context.Context) *userModelDo {
	return u.userModelDo.WithContext(ctx)
}

func (u userModel) TableName() string { return u.userModelDo.TableName() }

func (u userModel) Alias() string { return u.userModelDo.Alias() }

func (u *userModel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userModel) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 6)
	u.fieldMap["id"] = u.ID
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["updated_at"] = u.UpdatedAt
	u.fieldMap["deleted_at"] = u.DeletedAt
	u.fieldMap["email_address"] = u.EmailAddress
	u.fieldMap["phone_number"] = u.PhoneNumber
}

func (u userModel) clone(db *gorm.DB) userModel {
	u.userModelDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userModel) replaceDB(db *gorm.DB) userModel {
	u.userModelDo.ReplaceDB(db)
	return u
}

type userModelDo struct{ gen.DO }

func (u userModelDo) Debug() *userModelDo {
	return u.withDO(u.DO.Debug())
}

func (u userModelDo) WithContext(ctx context.Context) *userModelDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userModelDo) ReadDB() *userModelDo {
	return u.Clauses(dbresolver.Read)
}

func (u userModelDo) WriteDB() *userModelDo {
	return u.Clauses(dbresolver.Write)
}

func (u userModelDo) Session(config *gorm.Session) *userModelDo {
	return u.withDO(u.DO.Session(config))
}

func (u userModelDo) Clauses(conds ...clause.Expression) *userModelDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userModelDo) Returning(value interface{}, columns ...string) *userModelDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userModelDo) Not(conds ...gen.Condition) *userModelDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userModelDo) Or(conds ...gen.Condition) *userModelDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userModelDo) Select(conds ...field.Expr) *userModelDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userModelDo) Where(conds ...gen.Condition) *userModelDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userModelDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *userModelDo {
	return u.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (u userModelDo) Order(conds ...field.Expr) *userModelDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userModelDo) Distinct(cols ...field.Expr) *userModelDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userModelDo) Omit(cols ...field.Expr) *userModelDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userModelDo) Join(table schema.Tabler, on ...field.Expr) *userModelDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userModelDo) LeftJoin(table schema.Tabler, on ...field.Expr) *userModelDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userModelDo) RightJoin(table schema.Tabler, on ...field.Expr) *userModelDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userModelDo) Group(cols ...field.Expr) *userModelDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userModelDo) Having(conds ...gen.Condition) *userModelDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userModelDo) Limit(limit int) *userModelDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userModelDo) Offset(offset int) *userModelDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userModelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *userModelDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userModelDo) Unscoped() *userModelDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userModelDo) Create(values ...*model.UserModel) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userModelDo) CreateInBatches(values []*model.UserModel, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userModelDo) Save(values ...*model.UserModel) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userModelDo) First() (*model.UserModel, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserModel), nil
	}
}

func (u userModelDo) Take() (*model.UserModel, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserModel), nil
	}
}

func (u userModelDo) Last() (*model.UserModel, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserModel), nil
	}
}

func (u userModelDo) Find() ([]*model.UserModel, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserModel), err
}

func (u userModelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserModel, err error) {
	buf := make([]*model.UserModel, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userModelDo) FindInBatches(result *[]*model.UserModel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userModelDo) Attrs(attrs ...field.AssignExpr) *userModelDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userModelDo) Assign(attrs ...field.AssignExpr) *userModelDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userModelDo) Joins(fields ...field.RelationField) *userModelDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userModelDo) Preload(fields ...field.RelationField) *userModelDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userModelDo) FirstOrInit() (*model.UserModel, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserModel), nil
	}
}

func (u userModelDo) FirstOrCreate() (*model.UserModel, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserModel), nil
	}
}

func (u userModelDo) FindByPage(offset int, limit int) (result []*model.UserModel, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userModelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userModelDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userModelDo) Delete(models ...*model.UserModel) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userModelDo) withDO(do gen.Dao) *userModelDo {
	u.DO = *do.(*gen.DO)
	return u
}
