// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/israel-duff/ledger-system/pkg/db/model"
)

func newWalletType(db *gorm.DB, opts ...gen.DOOption) walletType {
	_walletType := walletType{}

	_walletType.walletTypeDo.UseDB(db, opts...)
	_walletType.walletTypeDo.UseModel(&model.WalletType{})

	tableName := _walletType.walletTypeDo.TableName()
	_walletType.ALL = field.NewAsterisk(tableName)
	_walletType.ID = field.NewString(tableName, "id")
	_walletType.CreatedAt = field.NewTime(tableName, "created_at")
	_walletType.UpdatedAt = field.NewTime(tableName, "updated_at")
	_walletType.DeletedAt = field.NewField(tableName, "deleted_at")
	_walletType.Name = field.NewString(tableName, "name")
	_walletType.Rules = field.NewString(tableName, "rules")
	_walletType.OwnerID = field.NewString(tableName, "owner_id")

	_walletType.fillFieldMap()

	return _walletType
}

type walletType struct {
	walletTypeDo walletTypeDo

	ALL       field.Asterisk
	ID        field.String
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field
	Name      field.String
	Rules     field.String
	OwnerID   field.String

	fieldMap map[string]field.Expr
}

func (w walletType) Table(newTableName string) *walletType {
	w.walletTypeDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w walletType) As(alias string) *walletType {
	w.walletTypeDo.DO = *(w.walletTypeDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *walletType) updateTableName(table string) *walletType {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewString(table, "id")
	w.CreatedAt = field.NewTime(table, "created_at")
	w.UpdatedAt = field.NewTime(table, "updated_at")
	w.DeletedAt = field.NewField(table, "deleted_at")
	w.Name = field.NewString(table, "name")
	w.Rules = field.NewString(table, "rules")
	w.OwnerID = field.NewString(table, "owner_id")

	w.fillFieldMap()

	return w
}

func (w *walletType) WithContext(ctx context.Context) *walletTypeDo {
	return w.walletTypeDo.WithContext(ctx)
}

func (w walletType) TableName() string { return w.walletTypeDo.TableName() }

func (w walletType) Alias() string { return w.walletTypeDo.Alias() }

func (w walletType) Columns(cols ...field.Expr) gen.Columns { return w.walletTypeDo.Columns(cols...) }

func (w *walletType) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *walletType) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 7)
	w.fieldMap["id"] = w.ID
	w.fieldMap["created_at"] = w.CreatedAt
	w.fieldMap["updated_at"] = w.UpdatedAt
	w.fieldMap["deleted_at"] = w.DeletedAt
	w.fieldMap["name"] = w.Name
	w.fieldMap["rules"] = w.Rules
	w.fieldMap["owner_id"] = w.OwnerID
}

func (w walletType) clone(db *gorm.DB) walletType {
	w.walletTypeDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w walletType) replaceDB(db *gorm.DB) walletType {
	w.walletTypeDo.ReplaceDB(db)
	return w
}

type walletTypeDo struct{ gen.DO }

func (w walletTypeDo) Debug() *walletTypeDo {
	return w.withDO(w.DO.Debug())
}

func (w walletTypeDo) WithContext(ctx context.Context) *walletTypeDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w walletTypeDo) ReadDB() *walletTypeDo {
	return w.Clauses(dbresolver.Read)
}

func (w walletTypeDo) WriteDB() *walletTypeDo {
	return w.Clauses(dbresolver.Write)
}

func (w walletTypeDo) Session(config *gorm.Session) *walletTypeDo {
	return w.withDO(w.DO.Session(config))
}

func (w walletTypeDo) Clauses(conds ...clause.Expression) *walletTypeDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w walletTypeDo) Returning(value interface{}, columns ...string) *walletTypeDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w walletTypeDo) Not(conds ...gen.Condition) *walletTypeDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w walletTypeDo) Or(conds ...gen.Condition) *walletTypeDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w walletTypeDo) Select(conds ...field.Expr) *walletTypeDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w walletTypeDo) Where(conds ...gen.Condition) *walletTypeDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w walletTypeDo) Order(conds ...field.Expr) *walletTypeDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w walletTypeDo) Distinct(cols ...field.Expr) *walletTypeDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w walletTypeDo) Omit(cols ...field.Expr) *walletTypeDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w walletTypeDo) Join(table schema.Tabler, on ...field.Expr) *walletTypeDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w walletTypeDo) LeftJoin(table schema.Tabler, on ...field.Expr) *walletTypeDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w walletTypeDo) RightJoin(table schema.Tabler, on ...field.Expr) *walletTypeDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w walletTypeDo) Group(cols ...field.Expr) *walletTypeDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w walletTypeDo) Having(conds ...gen.Condition) *walletTypeDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w walletTypeDo) Limit(limit int) *walletTypeDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w walletTypeDo) Offset(offset int) *walletTypeDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w walletTypeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *walletTypeDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w walletTypeDo) Unscoped() *walletTypeDo {
	return w.withDO(w.DO.Unscoped())
}

func (w walletTypeDo) Create(values ...*model.WalletType) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w walletTypeDo) CreateInBatches(values []*model.WalletType, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w walletTypeDo) Save(values ...*model.WalletType) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w walletTypeDo) First() (*model.WalletType, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.WalletType), nil
	}
}

func (w walletTypeDo) Take() (*model.WalletType, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.WalletType), nil
	}
}

func (w walletTypeDo) Last() (*model.WalletType, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.WalletType), nil
	}
}

func (w walletTypeDo) Find() ([]*model.WalletType, error) {
	result, err := w.DO.Find()
	return result.([]*model.WalletType), err
}

func (w walletTypeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WalletType, err error) {
	buf := make([]*model.WalletType, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w walletTypeDo) FindInBatches(result *[]*model.WalletType, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w walletTypeDo) Attrs(attrs ...field.AssignExpr) *walletTypeDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w walletTypeDo) Assign(attrs ...field.AssignExpr) *walletTypeDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w walletTypeDo) Joins(fields ...field.RelationField) *walletTypeDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w walletTypeDo) Preload(fields ...field.RelationField) *walletTypeDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w walletTypeDo) FirstOrInit() (*model.WalletType, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.WalletType), nil
	}
}

func (w walletTypeDo) FirstOrCreate() (*model.WalletType, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.WalletType), nil
	}
}

func (w walletTypeDo) FindByPage(offset int, limit int) (result []*model.WalletType, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w walletTypeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w walletTypeDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w walletTypeDo) Delete(models ...*model.WalletType) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *walletTypeDo) withDO(do gen.Dao) *walletTypeDo {
	w.DO = *do.(*gen.DO)
	return w
}
