// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAPIKey = "api_keys"

// APIKey mapped from table <api_keys>
type APIKey struct {
	ID            string         `gorm:"column:id;primaryKey;default:uuid_generate_v4()" json:"id"`
	CreatedAt     time.Time      `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt     time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	TestSecretKey string         `gorm:"column:test_secret_key;not null" json:"test_secret_key"`
	TestPublicKey string         `gorm:"column:test_public_key;not null" json:"test_public_key"`
	LiveSecretKey string         `gorm:"column:live_secret_key;not null" json:"live_secret_key"`
	LivePublicKey string         `gorm:"column:live_public_key;not null" json:"live_public_key"`
	OwnerID       string         `gorm:"column:owner_id;not null" json:"owner_id"`
}

// TableName APIKey's table name
func (*APIKey) TableName() string {
	return TableNameAPIKey
}
