// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameLedgerTransaction = "ledger_transactions"

// LedgerTransaction mapped from table <ledger_transactions>
type LedgerTransaction struct {
	ID          string         `gorm:"column:id;primaryKey;default:uuid_generate_v4()" json:"id"`
	CreatedAt   time.Time      `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Description string         `gorm:"column:description;not null" json:"description"`
	Status      string         `gorm:"column:status;not null" json:"status"`
}

// TableName LedgerTransaction's table name
func (*LedgerTransaction) TableName() string {
	return TableNameLedgerTransaction
}
