// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameLedgerAccount = "ledger_accounts"

// LedgerAccount mapped from table <ledger_accounts>
type LedgerAccount struct {
	ID                   string         `gorm:"column:id;primaryKey;default:uuid_generate_v4()" json:"id"`
	CreatedAt            time.Time      `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt            time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt            gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	AccountNumber        string         `gorm:"column:account_number;not null" json:"account_number"`
	Status               string         `gorm:"column:status;not null" json:"status"`
	Book                 string         `gorm:"column:book;not null" json:"book"`
	Particular           string         `gorm:"column:particular;not null" json:"particular"`
	OwnerID              string         `gorm:"column:owner_id" json:"owner_id"`
	Label                string         `gorm:"column:label" json:"label"`
	CurrentActiveBlockID string         `gorm:"column:current_active_block_id;not null" json:"current_active_block_id"`
	BlockCount           int32          `gorm:"column:block_count;not null" json:"block_count"`
}

// TableName LedgerAccount's table name
func (*LedgerAccount) TableName() string {
	return TableNameLedgerAccount
}
