// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserModel = "user_models"

// UserModel mapped from table <user_models>
type UserModel struct {
	ID           string         `gorm:"column:id;primaryKey" json:"id"`
	CreatedAt    time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	EmailAddress string         `gorm:"column:email_address" json:"email_address"`
	PhoneNumber  string         `gorm:"column:phone_number" json:"phone_number"`
}

// TableName UserModel's table name
func (*UserModel) TableName() string {
	return TableNameUserModel
}
