// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameWalletType = "wallet_type"

// WalletType mapped from table <wallet_type>
type WalletType struct {
	ID        string         `gorm:"column:id;primaryKey;default:uuid_generate_v4()" json:"id"`
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Name      string         `gorm:"column:name;not null" json:"name"`
	Rules     string         `gorm:"column:rules;not null" json:"rules"`
	OwnerID   string         `gorm:"column:owner_id;not null" json:"owner_id"`
}

// TableName WalletType's table name
func (*WalletType) TableName() string {
	return TableNameWalletType
}
