// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameWallet = "wallet"

// Wallet mapped from table <wallet>
type Wallet struct {
	ID             string         `gorm:"column:id;primaryKey;default:uuid_generate_v4()" json:"id"`
	CreatedAt      time.Time      `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt      time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Name           string         `gorm:"column:name;not null" json:"name"`
	Type           string         `gorm:"column:type;not null" json:"type"`
	AccountNumber  string         `gorm:"column:account_number;not null" json:"account_number"`
	LedgerAccounts string         `gorm:"column:ledger_accounts;not null" json:"ledger_accounts"`
	OwnerID        string         `gorm:"column:owner_id;not null" json:"owner_id"`
}

// TableName Wallet's table name
func (*Wallet) TableName() string {
	return TableNameWallet
}
